version: "3.9"

services:
  model_server:
    build:
      context: ./model_server
    container_name: batchlabellingpipelineimages-model_server
    ports:
      - "8000:8000"
    volumes:
      - ./loadedimages:/app/loadedimages
      - ./model_server:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
